Repository microsoft/helium-java, pull requests merged in 2019-06, with the labels that each got.

#1 Initial project structure
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  LICENSE
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/microsoft/azure/helium/DemoApplication.java
  src/main/resources/application.properties
  src/test/java/com/microsoft/azure/helium/DemoApplicationTests.java
Labels: feature

#11 feat: adding actors, genres, movies and system controllers
  src/main/java/com/microsoft/azure/helium/SwaggerConfig.java
  src/main/java/com/microsoft/azure/helium/config/SwaggerConfig.java
  src/main/java/com/microsoft/azure/helium/controller/ActorsController.java
  src/main/java/com/microsoft/azure/helium/controller/GenresController.java
  src/main/java/com/microsoft/azure/helium/controller/MoviesController.java
  src/main/java/com/microsoft/azure/helium/controller/SystemController.java
  src/main/java/com/microsoft/azure/helium/model/Actor.java
  src/main/java/com/microsoft/azure/helium/model/Movie.java
  src/test/java/com/microsoft/azure/helium/SmokeTests.java
  src/test/java/com/microsoft/azure/helium/controller/ControllerTests.java
Labels: feature

#14 feat: Dockerfile, pom file, rename main class #3
  Dockerfile
  pom.xml
  src/main/java/com/microsoft/azure/helium/Application.java
Labels: feature

#16 Update azure-pipelines.yml for Azure Pipelines
  azure-pipelines.yml
Labels: feature

#17 fix: Update azure-pipelines.yml for Azure Pipelines #4
  azure-pipelines.yml
Labels: enhancement

#24 fix: caching Docker builds + .dockerignore
  Dockerfile
  pom.xml
  src/.dockerignore
Labels: enhancement

#29 fix: fixing dockerignore
  .dockerignore
Labels: enhancement

#35 feat: azure key-vault spring boot starter
  pom.xml
  src/main/java/com/microsoft/azure/helium/config/RepositoryConfig.java
  src/main/resources/application.properties
Labels: feature

#38 docs: doc folder and files structure
  docs/azure-cosmosdb.md
  docs/azure-keyvault.md
  docs/azure-monitor.md
  docs/deploying-helium-java.md
  docs/imgs/appinsightRG.png
  docs/imgs/appinsightdash.png
  docs/imgs/cosmosdash.png
  docs/imgs/dashselection.png
  docs/imgs/edit.png
  docs/imgs/editmetric.png
  docs/imgs/editresourceg.png
  docs/imgs/pintodash.png
  docs/imgs/portal.png
  docs/imgs/share.png
  docs/imgs/tilegallery.png
Labels: documentation
